### DISCUSSION TITLE
example for using a datasource as a subdataset in jasper report without using a subreport

### DISCUSSION THREAD

**Discussion by simonseyock** [mapfish/mapfish-print#3219] [Show and tell]
I struggled some time to use the datasource created by `!datasource` and `!createDatasource` as a subdataset in jasper. I wanted to share my findings as the documentation is very unclear in that regard (it is not explained how the datasource is treated inside jasper and what is provided to the report and how to read that). So here it is:

config.yaml
```yaml
templates:
  name: !template
    attributes:
      data: !datasource
        attributes:
          key1: !string {}
          key2: !string {}
    processors:
      - !reportBuilder
        directory: '.'
      - !createDataSource
        processors: []
        inputMapper:
          data: datasource
        outputMapper:
          jrDataSource: someDatasource
```

report.jrxml (excerpts)
```xml
<subDataset name="someDataset">
  <queryString>
    <![CDATA[]]>
  </queryString>
  <field name="key1" class="java.lang.String"/>
  <field name="key2" class="java.lang.String"/>
</subDataset>
<!-- ... -->
<parameter name="someDatasource" class="net.sf.jasperreports.engine.JRDataSource"/>
<!-- ... -->
<datasetRun subDataset="someDataset">
  <dataSourceExpression>$P{someDatasource}</dataSourceExpression>
</datasetRun>
```

Cheers :beers:
