### ISSUE TITLE
config.yaml: The position of !configureHttpRequests in the processors section

### ISSUE THREAD

**Issue by marshall79** [mapfish/mapfish-print#1063]
We have two systems where we have installed mapfish-print 3.19.0, a system for testing and an operating sytem. Now we have to notice that it makes a difference in the resulting pdf depending on whether the !configureHttpRequests is at the beginning or at the end of the processors section.

Is it at the beginning it works fine at the operating system. But there are pink images in legend and map in the resulted pdf created at the testing system. 

`processors:`
```
     - !configureHttpRequests
        httpProcessors:
          - !mapUri
            mapping:
              https://......... : "http://....."
              ...
              ...
     # compile all reports in current directory 
     - !reportBuilder 
        directory: '.'
      - !createMap {}
      - !createNorthArrow {}
      - !createScalebar {}
      - !prepareLegend
        template: legend.jrxml
```

It's a reverse behaviour if we put the !configureHttpRequests at the end of the processors section. Now the testing system works fine, but the pink images are in the resulted pdf created at the operating system.

`processors:`
```
      - !reportBuilder 
        directory: '.'
      - !createMap {}
      - !createNorthArrow {}
      - !createScalebar {}
      - !prepareLegend
        template: legend.jrxml
      - !configureHttpRequests
        httpProcessors:
          - !mapUri
            mapping:
              https://......... : "http://....."
              ...
              ...
      # compile all reports in current directory
      - !reportBuilder 
        directory: '.'   
``` 
What can be the reason for this (settings, installation, ... ) and which order is the right?
