### ISSUE TITLE
Legend Block - Base Font

### ISSUE THREAD

**Issue by geekdenz** [mapfish/mapfish-print#14]
When printing a legend a base font like Arial causes an exception to be thrown. Can be reproduced by putting something like the following into config.yaml:

```
lastPage:
  pageSize: A4
  items:
    - !columns
      absoluteX: 80
      absoluteY: 745
      width: 450
      items:
        - !text
          align: left
          font: Arial
          fontSize: 16
          text: 'Legend'
    - !columns
      absoluteX: 80
      absoluteY: 715
      width: 450
      items:
        - !legends
          backgroundColor: #FFFFFF
          maxIconWidth: 20
          maxIconHeight: 20
          classIndentation: 0
          layerSpace: 25
          classSpace: 10
          layerFont: Arial
          layerFontSize: 14
          classFont: Arial
          classFontSize: 12
          fontEncoding: Cp1252
```

I have a fix for this issue and will make a pull request for someone else to review.
