### ISSUE TITLE
Scalebar fontColor.

### ISSUE THREAD

**Issue by sweco-sehrbe** [mapfish/mapfish-print#141]
The "fontColor:" attribute is not honored for the scalebar block, as documented.

Snippet from config.yaml

``` yaml
          items:
            - !scalebar
              type: bar
              maxSize: 100
              barBgColor: white
              fontColor: 'ff0000'
              fontSize: 9
              font: Helvetica Neue
              align: left
```

Image of generated PDF. Scalebar text not red.

![utskrift_pdf](https://cloud.githubusercontent.com/assets/4488524/4075235/c828f1c0-2eac-11e4-9120-3833907e5706.png)
