### ISSUE TITLE
outputFilename

### ISSUE THREAD

**Issue by stesz007** [mapfish/mapfish-print#1563]
The JSON File defines the outputFilename correctly:

{"layout":"1. A4 Querformat","outputFilename":"Druck","outputFormat":"pdf","attributes":{"title":"Mein Titel","map":{"dpi":200,"projection":"EPSG:25832","center":[385000,5530000],"scale":500,"layers":[{"baseURL":"https://geo4.service24.rlp.de/wms/shade.fcgi","opacity":0.25,"type":"WMS","layers":["rp_shade10m"],"imageFormat":"image/png","customParams":{"TRANSPARENT":"true"}},{"baseURL":"https://sgx.geodatenzentrum.de/wms_topplus_open","opacity":1,"type":"WMS","layers":["web"],"imageFormat":"image/png","customParams":{"TRANSPARENT":"true"}}]},"scale":"1:500"}}: 

but the file the browser gives back will be not overwrited in "Druck.pdf". It is the same filename as in the directory itself:

example:
 https://masterportal.service24.rlp.de/portale/zus_finder/printer/print/report/f10e5ff3-b4eb-4d66-be47-c2c14fd09fb1@de96c402-0332-462b-8ba2-db0d9b60070e

Is this an configuration problem?

**Comment by sbrunner** [comment]
You probably have defined it in the config.yaml, it's taken in priority...

**Comment by stesz007** [comment]
In the yaml file there ist no options configured for using uuid as filename. The suffix will also not be written.

Example:
```
  #===========================================================================	
  4. A3 Querformat: !template
  #===========================================================================
    reportTemplate: a3_querformat.jrxml
    attributes:
      title: !string {}
      scale: !string {}
      map: !map
        maxDpi: 400
        dpiSuggestions: [72, 96, 120, 400]
        width: 1121
        height: 675
        zoomLevels: !zoomLevels
          scales: [500, 1000, 2000, 2500, 5000, 10000, 25000, 50000, 100000, 250000]
      scalebar: !scalebar
        width: 140
        height: 30
        default:
          barSize: 2
          type: bar
          align: left
          intervals: 4
          lineWidth: 1
          font: Helvetica
          fontSize: 8
      overlayLayers: !staticLayers
        default:
          layers:
            - type: "grid"
              numberOfLines: [0, 0]
              labelColor: rgba(0,0,0,0)
              haloColor: rgba(0,0,0,0)
    processors:
    - !addBackgroundLayers
      inputMapper:
          overlayLayers: staticLayers
          map: map
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap {}
    - !createScalebar {}

 ```

**Comment by sbrunner** [comment]
Your config is partial and don't contain the part where it can be defined, example of definition:
https://github.com/mapfish/mapfish-print/blob/313c4136cd078ccf09e5a3159d4ee43c9f19842e/core/src/test/resources/org/mapfish/print/servlet/config-email-s3.yaml#L3

**Comment by stesz007** [comment]
I test your config, but without positive result.

```
proxies:
  - !proxy
    scheme: http
    host: proxy.rlp
    port: 8080

outputFilename: config_test_outputname-${yyyy}

templates:
 #===========================================================================	
  4. A3 Querformat: !template
  #===========================================================================
    reportTemplate: a3_querformat.jrxml

..........
```


Is it perhaps a proxy-problem. 
Everthing of the print is fine - only the filename and the suffix will not be written correctly.


https://masterportal.service24.rlp.de/portale/zus_finder/printer/print/report/e1912600-6f41-452d-a570-0a887d389c50@79f851f4-5a8a-41fe-a774-422d71bd7c2e
