### ISSUE TITLE
Datasource with multiple type attribute

### ISSUE THREAD

**Issue by mafo113** [mapfish/mapfish-print#1890]
Hi everyone, 

I would like to use mapfish in order to print either multiple maps, multiple  tables or multiple images in a report. To do that, I tried the datasource attribute. This work great when you specify only one type of attribute ( table OR map see example datasource_multiple_maps). 

I would like to know how I could mix tables AND maps in a datasource and how it would work in the jasperreport and the config.yaml.

 I would like to request this kind of datasource : 

```json
 datasource: [
   {
        "table": {
          "columns": [
            "id",
            "name",
            "icon"
          ],
          "data": [
            [
              1,
              "blah",
              "icon_pan"
            ],
            [
              2,
              "blip",
              "icon_zoomin"
            ]
          ]
        },
      "map": {
          "projection": "EPSG:3857",
          "dpi": 72,
          "center": [
            -8233518.5005945,
            4980320.4059228
          ],
          "scale": 25000,
          "layers": [
            {
              "type": "geojson",
              "style": {
                "*": {
                  "symbolizers": [
                    {
                      "fillColor": "red",
                      "strokeColor": "red",
                      "strokeOpacity": 1,
                      "strokeWidth": 2,
                      "pointRadius": 6,
                      "type": "point"
                    }
                  ]
                },
                "version": "2"
              },
              "geoJson": {
                "type": "FeatureCollection",
                "features": [
                  {
                    "type": "Feature",
                    "properties": {
                      "name": "Lake View"
                    },
                    "geometry": {
                      "type": "Point",
                      "coordinates": [
                        -8233518.5005945,
                        4980320.4059228
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
   }, {
        "table": {
          "columns": [
            "id",
            "name",
            "icon"
          ],
          "data": [
            [
              1,
              "blah",
              "icon_pan"
            ],
            [
              2,
              "blip",
              "icon_zoomin"
            ]
          ]
        }
      "map": {
          "projection": "EPSG:3857",
          "dpi": 72,
          "center": [
            -8233518.5005945,
            4980320.4059228
          ],
          "scale": 25000,
          "layers": [
            {
              "type": "geojson",
              "style": {
                "*": {
                  "symbolizers": [
                    {
                      "fillColor": "red",
                      "strokeColor": "red",
                      "strokeOpacity": 1,
                      "strokeWidth": 2,
                      "pointRadius": 6,
                      "type": "point"
                    }
                  ]
                },
                "version": "2"
              },
              "geoJson": {
                "type": "FeatureCollection",
                "features": [
                  {
                    "type": "Feature",
                    "properties": {
                      "name": "Lake View"
                    },
                    "geometry": {
                      "type": "Point",
                      "coordinates": [
                        -8233518.5005945,
                        4980320.4059228
                      ]
                    }
                  }
                ]
              }
            }
          ]
        }
   }
 ]
```

my config. yaml so far : 

```yaml
throwErrorOnExtraParameters: true

templates:
  A4 portrait: !template
    reportTemplate: simpleReport.jrxml
    attributes:
      title: !string {}
      comments: !string {}
      datasource: !datasource
        table: !table {}
        map: !map
          maxDpi: 254
          width: 200
          height: 200

    processors:
      - !reportBuilder # compile all reports in current directory
        directory: '.'
      - !createDataSource
        reportTemplate: table.jrxml
        reportKey: reportTemplate
        processors:
          - !prepareTable {}
          - !createMap {}
    tableData: jrDataSource
```
