### ISSUE TITLE
How can i set the attribute dnsMatch?

### ISSUE THREAD

**Issue by hoytGMX** [mapfish/mapfish-print#229]
Hello everybody,

the attribute dnsMatch needs to be written to the config.yaml. But, at what point?
Here's what I've already tried:

1)
```
hosts:
- !dnsMatch
host: a.tile.openstreetmap.org
```
2)
```
dnsMatch: !dnsMatch
host: a.tile.openstreetmap.org
```

3)
Within the blocks processors oder attributes.

No matter what I do, I always get an error.
Like: Unable to find property 'dnsMatch' on class: org.mapfish.print.config.Configuration
Or: org.mapfish.print.processor.http.matcher.DnsHostMatcher cannot be cast to org.mapfish.print.processor.Processor

**Comment by tsauerwein** [comment]
Are you using MapFish Print 2 or 3?

For MapFish Print 3 the [http_processors example](https://github.com/mapfish/mapfish-print/blob/88428e7b662fd643fdffce494fb745033bcd2b34/examples/src/test/resources/examples/http_processors/config.yaml) will be helpful:



    processors:
    ...
    - !configureHttpRequests
      httpProcessors:
        - !restrictUris
          matchers:
            - !dnsMatch
              host: tile.openstreetmap.org
              port: 80

**Comment by hoytGMX** [comment]
I´m using the MapFish Print Version 3.
Your suggestion worked. Anyway, I get no errors.

Now I have another question, how can I print a simple map?
This is my config.yaml

```
templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: simpleReport.jrxml
    attributes:
      map: !map
        maxDpi: 400
        width: 780
        height: 330
    processors:
    - !configureHttpRequests
      httpProcessors:
        - !restrictUris
          matchers:
            - !dnsMatch
              host: a.tile.openstreetmap.org
              port: 80
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createMap
      inputMapper: {map: map}
      outputMapper: {mapSubReport: map}
```

This is my json:

```
{
	"layout": "A4 landscape",
	"outputFormat": "pdf",
	"attributes": 
	{
		"map": 
		{
			"projection": "EPSG:900913",
			"dpi": 72,
			"center": [700037.00694008, 6760056.1555205],
			"scale": 216671,
			"layers": 
			[
				{
		            "type": "osm",		            
		            "baseURL": "http://a.tile.openstreetmap.org/"		            
		        }
			]
		}
	}
}
```
I get the following error:
```
ERROR o.m.print.map.tiled.TileLoaderTask - Error making tile request: http://a.tile.openstreetmap.org/11/1058/679.png
        Status: 403
        Message: Forbidden
```
Unfortunately I could not solve the problem by the dnsMatch attribute.
Any suggestions?

**Comment by hoytGMX** [comment]
Small update:

I embed a WMS layer and adjusted the config.yaml. It works like a charme (:
Unfortunately, I still get an error when I try to integrate OSM.
What is the correct hostname?
I have already tried the following options, and every time I got no access.
```
config.yaml
host: a.tile.openstreetmap.org
or
host: tile.openstreetmap.org
```
Kind regards

**Comment by tsauerwein** [comment]
@hoytGMX I think tile.openstreetmap.org checks the user agent in the request header to restrict the usage. For testing purposes you could fake a browser user agent with `addHeaders` (see in this [example](https://github.com/mapfish/mapfish-print/blob/88428e7b662fd643fdffce494fb745033bcd2b34/examples/src/test/resources/examples/http_processors/config.yaml)), but please make sure to follow the usage restrictions of the OSM tile servers.

**Comment by hoytGMX** [comment]
Hey,

my config.yaml is as follows:

```
templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: simpleReport.jrxml
    tableData: jrDataSource
    outputFilename: Foobar
    attributes:
      scalebar: !scalebar
        width: 230
        height: 35
      map: !map
        maxDpi: 400
        width: 800
        height: 500        
      datasource: !datasource
        attributes:
            title: !string {}
            table: !table {}
    processors:
    - !configureHttpRequests
      httpProcessors:
        - !restrictUris
          matchers:            
            - !dnsMatch
              host: otile1.mqcdn.com
              port: -1
            - !dnsMatch
              host: otile2.mqcdn.com
              port: -1
            - !dnsMatch
              host: otile3.mqcdn.com
              port: -1
            - !dnsMatch
              host: otile4.mqcdn.com
              port: -1
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createScalebar {}
    - !createMap {}
    - !createDataSource
        processors:
        - !prepareTable
          dynamic: true
```

Sometimes it works and sometimes not. Anyway, I get the following error message.
*Error while processing request:
java.lang.IllegalArgumentException: http://otile1.mqcdn.com/tiles/1.0.0/map/13/4236/2715.jpg is not one of the permitted urls.*

The url is one of the permited urls (otile1.mqcdn.com)?! What causes this error message?

Best regards
