### ISSUE TITLE
proxy configuration

### ISSUE THREAD

**Issue by renegaebler** [mapfish/mapfish-print#2310]
Hi,

I need some help with my proxy configuration. Basically, it is possible to redirect all requests across the forward proxy over the Internet. However, some requests are intended to pass the forward proxy directly to local servers. In my organization, the MapFish print server is behind some firewalls and proxies. In this way, we can reduce the traffic and direct self-hosted services shortly to their target. 

My current configuration

```
#=====================================================================
#==   PROXY CONFIG 
#=====================================================================
proxies:  
  - !proxy
    scheme: http
    host: forward_proxy.to.www
    port: 3128
    matchers: 
    - !dnsMatch
      host: sample_request.host1.local
      reject: true
    - !acceptAll {}

proxies: 
  - !proxy
    scheme: http
    host: forward_proxy.to.www
    port: 3128
    matchers: 
    - !dnsMatch
      host: sample_request.host2.local
      reject: true
    - !acceptAll {}

proxies: 
  - !proxy
    scheme: http
    host: forward_proxy.to.www
    port: 3128
    matchers: 
    - !dnsMatch
      host: sample_request.host3.local
      reject: true
    - !acceptAll {}
#=====================================================================
```

A test proved that the requests are going to the proxy which they are actually not supposed to. It seems that only the first proxy matches, the second one doesn't.
Is it possible to use more than one proxy entry in the config.yaml file? If yes, is the syntax correct? Or should I choose all different hosts behind the matcher? both variants returned no error on deploy.

```
#=====================================================================
#==   PROXY CONFIG 
#=====================================================================
proxies:  
  - !proxy
    scheme: http
    host: forward_proxy.to.www
    port: 3128
    matchers: 
    - !dnsMatch
      host: sample_request.host1.local
      reject: true
    - !dnsMatch
      host: sample_request.host2.local
      reject: true
    - !dnsMatch
      host: sample_request.host3.local
      reject: true
    - !acceptAll {}
#=====================================================================
```

In order for this to happen, it isn't possible to list all the different sample_request.hosts separately. There are more than hundreds of hosts that have to go over the forward proxy and a few hosts should not go over it.
Is it possible to implement a support for regex terms?
