### ISSUE TITLE
Allow attributes to have default values

### ISSUE THREAD

**Issue by Jenselme** [mapfish/mapfish-print#252]
I would like to provide default values for some attributes to the client. Something like:
```yaml
attributes:
  name: !string
    default: "Coucou"
```
would be nice. Currently, this syntax is ignored.
