### ISSUE TITLE
mqcdn.com - is not one of the permitted urls

### ISSUE THREAD

**Issue by hoytGMX** [mapfish/mapfish-print#258]
Hey,

my config.yaml is as follows:
```
templates:
  #===========================================================================
  A4 landscape: !template
  #===========================================================================
    reportTemplate: simpleReport.jrxml
    tableData: jrDataSource
    outputFilename: Foobar
    attributes:
      scalebar: !scalebar
        width: 230
        height: 35
      map: !map
        maxDpi: 400
        width: 800
        height: 500        
      datasource: !datasource
        attributes:
            title: !string {}
            table: !table {}
    processors:
    - !configureHttpRequests
      httpProcessors:
        - !restrictUris
          matchers:            
            - !dnsMatch
              host: otile1.mqcdn.com
              port: -1
            - !dnsMatch
              host: otile2.mqcdn.com
              port: -1
            - !dnsMatch
              host: otile3.mqcdn.com
              port: -1
            - !dnsMatch
              host: otile4.mqcdn.com
              port: -1
    - !reportBuilder # compile all reports in current directory
      directory: '.'
    - !createScalebar {}
    - !createMap {}
    - !createDataSource
        processors:
        - !prepareTable
          dynamic: true
```
Sometimes it works and sometimes not. Anyway, I get the following error message.
Error while processing request:
java.lang.IllegalArgumentException: http://otile1.mqcdn.com/tiles/1.0.0/map/13/4236/2715.jpg is not one of the permitted urls.

The url is one of the permited urls (otile1.mqcdn.com)?! What causes this error message?

Best regards
