### ISSUE TITLE
Mapfish on Kubernetes

### ISSUE THREAD

**Issue by edwin** [mapfish/mapfish-print#3282]
hi team,

we are currently running Mapfish on Kubernetes environment and seeing intermittent OutOfMemoryError
right now we are using below configuration,

```
resources:
          limits:
            cpu: "3"
            memory: "10000Mi"
          requests:
            cpu: "0.5"
            memory: "5000Mi"
```

do we have some kind of basic Kubernetes configuration, health check urls, or pod sizing for this kind of deployment?

thank you.

**Comment by sbrunner** [comment]
Hello,
On our Kubernetes we use in prdocution:
```yaml

    resources:
      requests:
        memory: 3942Mi
        cpu: 1m
      limits:
        memory: 8Gi
        cpu: '2'
```
With that, we can print A0 in simple cases, but we limit the concurrent jobs to 2 with `-DmaxNumberOfRunningPrintJobs=2`.
