### ISSUE TITLE
add matches to http processors

### ISSUE THREAD

**Issue by sbrunner** [mapfish/mapfish-print#347]
Concerned processors:
ForwardHeadersProcessor
AddHeadersProcessor
UseHttpForHttpsProcessor in place of hosts ? (should be named MapPortProcessor ?)
MapUriProcessor ?
Others ?

Wanted config for GeoMapFish:
```yaml
        - !configureHttpRequests
            httpProcessors:
            - !mapUri
                match:
                - !dnsMatch
                    host: ${host}
                mapping:
                    (https?)://${host}/(.*): "$1://127.0.0.1/$2"
            - !portMapping
                match:
                - !dnsMatch
                    host: ${host}
                portMapping:
                    443: 80
            - !forwardHeaders
                match:
                - !dnsMatch
                    host: ${host}
                headers:
                - Cookie
                - Host
            - !forwardHeaders
                headers:
                - Referer
```

see also: https://github.com/mapfish/mapfish-print/pull/321#issuecomment-144737619
