### ISSUE TITLE
Word Wrap is over-zealous

### ISSUE THREAD

**Issue by jonathan-wcc** [mapfish/mapfish-print#57]
As you can see in the screencap, word-wrap is over-zealous. Even though my legend is set to a max width of 500, as is the containing column, its still wrapped "Subregion boundary" onto two lines.

![clipboard04](https://f.cloud.github.com/assets/3763600/586222/47d5e1ce-c948-11e2-8829-1fb6b2786890.jpg)

I don't think there's anything in my YAML saying to do that, but just in case, it's here:

```
    #Legend
    - !columns
      #This line determines if the legend is shown in the template.
      condition: legends
      absoluteX: 37
      absoluteY: 560
      width: 150
      config:
        borderWidth: 1
        cells:
          - borderWidth: 1
            borderColor: #555555
            padding: 5

      items:
        - !legends
          iconMaxWidth: 9
          iconMaxHeight: 9
          maxWidth: 150
          #Padding between layers
          layerSpace: 5
          layerFont: Helvetica
          layerFontSize: 9
          #Padding between text and icon within layer
          classSpace: 2
          classIndentation: 5
          classFont: Helvetica
          classFontSize: 9
          backgroundColor: white
          inline:true
```

Using MFP 1.2
