### ISSUE TITLE
minMargin in zoomToFeatures alter the map

### ISSUE THREAD

**Issue by ger-benjamin** [mapfish/mapfish-print#651]
It seems that the bigger your minMargin (in map->default->zoomToFeatures) is, the more deformed is your map.

An example with a minMargin of 0:
![selection_063](https://user-images.githubusercontent.com/1792111/35510761-b24309c8-04f9-11e8-8b69-58b2fc07e88c.png)

The same with a minMargin of 280px:
![selection_067](https://user-images.githubusercontent.com/1792111/35510851-11dd3430-04fa-11e8-98d6-5945fae03d2b.png)

The same with minMargin: 140px:
![selection_069](https://user-images.githubusercontent.com/1792111/35511081-eac729fe-04fa-11e8-9f64-3b417a0f2fd8.png)

The same with minMargin: 70px:
![selection_068](https://user-images.githubusercontent.com/1792111/35510985-8a4a5c40-04fa-11e8-8af2-3e7253238e55.png)

The map Config:
````
                map: !map                                                        
                    maxDpi: 254                                                  
                    dpiSuggestions: [254]                                        
                    width: 493                                                   
                    height: 280                                                  
                    default:                                                     
                        projection: "EPSG:2056"                                  
                        dpi: 72                                                  
                        zoomToFeatures:                                          
                            minScale: 10                                         
                            minMargin: 0  
````

Can you confirm the issue ? I'm not 100% sure that doesn't come from my application.
Edit note: I can only reproduce it with MinMargin. MinScale works well.
