### ISSUE TITLE
Per app referer check

### ISSUE THREAD

**Issue by pvalsecc** [mapfish/mapfish-print#699]
For all the HTTP APIs specific to an application, we should allow to specify the list of allowed referers.

Something like that at the root of the config.yaml:

```yaml
allowedReferers:
  - baseHostname: example.com
  - baseHostname: www.example2.com
```

With that example:

* example.com: allowed
* www.example.com: allowed
* otherexample.com: denied
* www2.example2.com: denied
* www.example.com: allowed
* xxx.www.example.com: allowed

Or better, use the URIMatcher class hierarchy. But the hostname matcher will need some improvements to allow sub domains wildcards.
